apiVersion: apps/v1
kind: Deployment
metadata: 
  name: signin-deployment
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: shoppingapp
  template:
    metadata:
      labels:
        app: shoppingapp
    spec:
      containers:
      - name: signin-container
        image: aakashbodade/signin
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: signin-service
spec:
  selector:
    app: shoppingapp
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
